name = "anthony-teaches-app"
account_id = '74829c5b0d7ab48291e8419849c18b8a'
zone_id = 'f3dfb6317ab30d364f16d02fc0e1bccb'

usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-28"

type = "javascript"


kv_namespaces = [
         { binding = "CONTACTS", id = "235f7ed9f6004a17afef85190a931dd4" }  
]

[build]
# Assume it's already been built. You can make this "npm run build" to ensure a build before publishing
command = ""

[build.upload]
format = "modules"
main = "./worker.mjs"

[site]
bucket = "./build"
entry-point = "./dist"